version: '3'
services:
  expo:
    build: .
    environment:
     - EXPO_USERNAME=${EXPO_USERNAME}
     - EXPO_PASSWORD=${EXPO_PASSWORD}
    ports:
     - "19000:19000"
     - "19001:19001"
     - "19002:19002"
     - "19003:19003"
     - "19004:19004"
     - "19005:19005"
    command: npm start
